#!/bin/bash

NAME=PHP
BASE_REPO=php
VARIANTS=(browsers node node-browsers)

TAG_FILTER="grep -v -e rc -e beta"

IMAGE_CUSTOMIZATIONS=$(cat <<'EOF'

RUN echo 'Defaults    env_keep += "PHP_INI_DIR"' >> /etc/sudoers.d/env_keep

# Install composer
RUN php -r "copy('https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

# Install XDebug
RUN (pecl install xdebug || pecl install xdebug-2.5.5 || pecl install xdebug-2.7.1) && docker-php-ext-enable xdebug

# Install common extensions
RUN apt install -y libicu-dev zlib1g-dev libzip-dev

# Install XDebug
RUN git clone https://github.com/websupport-sk/pecl-memcache
RUN cd pecl-memcache && \
    phpize && \
    ./configure && \
    make && \
    make install

# Install common extensions
RUN docker-php-ext-configure intl && docker-php-ext-install intl
RUN docker-php-ext-install zip
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install sockets
RUN docker-php-ext-enable memcache

# PHP Config
RUN echo -e "memory_limit = 256M" | sudo tee /usr/local/etc/php/conf.d/memory.ini > /dev/null

EOF
)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
